# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d81d85f8c25dabfef748dd6c4ab18bab748d2e46caca57210af5bd340229ebb23e819f5f0bbd3217e9a28e2140478578f5e750b581c31fd82bc0feeb515b5e

test:
  secret_key_base: 835817a4fa638f56f9bc66fef586c8dbe5a81844f708f1b0d6db6b870978402dc70851f2c2da6247621e157c09a7c6693e84a78a01b41daa318dc5b501e67491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
